/**
 * Set of color defs for nivo charts
 * @author Aryan Pandey
 * @author Grace Whitney
 */
export default {
  BLUE: {
    id: 'blue',
    background: '#385788',
    color: '#1F3E6F',
    type: 'patternLines',
    lineWidth: 2,
    spacing: 8,
    rotation: 45,
  },
  GREEN: {
    id: 'green',
    background: '#6B9551',
    color: '#527C38',
    type: 'patternDots',
    size: 3,
    padding: 4,
    stagger: true,
  },
  YELLOW: {
    id: 'yellow',
    background: '#DEA451',
    color: '#C58B38',
    type: 'patternSquares',
    size: 4,
    padding: 6,
  },
  RED: {
    id: 'red',
    background: '#AD3A36',
    color: '#94211D',
    type: 'patternLines',
    lineWidth: 2,
    spacing: 6,
    rotation: 0,
  },
  PURPLE: {
    id: 'purple',
    background: '#693F75',
    color: '#50265C',
    type: 'patternDots',
    size: 4,
    padding: 4,
  },
  ALT_BLUE: {
    id: 'alt-blue',
    background: '#385788',
    color: '#1F3E6F',
    type: 'patternSquares',
    size: 4,
    spacing: 8,
    stagger: true,
  },
  ALT_GREEN: {
    id: 'alt-green',
    background: '#6B9551',
    color: '#527C38',
    type: 'patternLines',
    lineWidth: 2,
    spacing: 8,
    rotation: -45,
  },
  ALT_YELLOW: {
    id: 'alt-yellow',
    background: '#DEA451',
    color: '#C58B38',
    type: 'patternDots',
    size: 6,
    padding: 5,
    stagger: true,
  },
  ALT_RED: {
    id: 'alt-red',
    background: '#AD3A36',
    color: '#94211D',
    type: 'patternSquares',
    size: 7,
    padding: 7,
  },
  ALT_PURPLE: {
    id: 'alt-purple',
    background: '#693F75',
    color: '#50265C',
    type: 'patternLines',
    lineWidth: 3,
    spacing: 7,
    rotation: 90,
  },
  GRAY: {
    id: 'gray',
    background: '#CCCCCC',
    color: '#BBBBBB',
    type: 'patternLines',
    size: 4,
    spacing: 4,
    rotation: 90,
  },
};
