/**
 * Set of color defs for nivo charts
 * @author Aryan Pandey
 * @author Grace Whitney
 */
export default {
  BLUE: {
    id: 'blue',
    background: '#33A0E4',
    color: '#136090',
    type: 'patternLines',
    lineWidth: 2,
    spacing: 8,
    rotation: 45,
  },
  ORANGE: {
    id: 'orange',
    background: '#F39A27',
    color: '#AE670A',
    type: 'patternDots',
    size: 2,
    padding: 4,
  },
  PURPLE: {
    id: 'purple',
    background: '#A981D4',
    color: '#783EB6',
    type: 'patternSquares',
    size: 4,
    padding: 6,
  },
  GREEN: {
    id: 'green',
    background: '#33B16D',
    color: '#206F45',
    type: 'patternLines',
    lineWidth: 2,
    spacing: 8,
    rotation: -45,
  },
  LIGHT_BLUE: {
    id: 'lightBlue',
    background: '#B6E9F9',
    color: '#68D2F3',
    type: 'patternDots',
    size: 4,
    padding: 4,
    stagger: true,
  },
  RED: {
    id: 'red',
    background: '#B20000',
    color: '#7A0002',
    type: 'patternSquares',
    size: 8,
    padding: 8,
  },
  YELLOW: {
    id: 'yellow',
    background: '#FFF771',
    color: '#DDDDDD',
    type: 'patternLines',
    lineWidth: 2,
    spacing: 6,
    rotation: 0,
  },
  PINK: {
    id: 'pink',
    background: '#FFD1E9',
    color: '#FF99CE',
    type: 'patternDots',
    size: 4,
    padding: 10,
  },
  TURQUOISE: {
    id: 'turquoise',
    background: '#00D1E1',
    color: '#00858F',
    type: 'patternSquares',
    size: 5,
    padding: 5,
  },
  LIGHT_GREEN: {
    id: 'lightGreen',
    background: '#B4E9A9',
    color: '#71D55D',
    type: 'patternLines',
    rotation: 90,
    lineWidth: 3,
    spacing: 9,
  },
  GRAY: {
    id: 'gray',
    background: '#DADEE3',
    color: '#CCCCCC',
    type: 'patternDots',
    size: 8,
    padding: 3,
    stagger: true,
  },
};
